services:
  - type: web
    name: control-piezas
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://control-piezas.onrender.com
      - key: ASSET_URL
        value: https://control-piezas.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /data/database.sqlite
